"""add session_todos table

Revision ID: 1fbb97d8845d
Revises: ab50175031af
Create Date: 2026-06-16 19:58:22.618040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbb97d8845d'
down_revision: Union[str, Sequence[str], None] = 'ab50175031af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_todos',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('todos_json', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_todos')
    # ### end Alembic commands ###
