"""init session store schema

Revision ID: e015eb383395
Revises: 
Create Date: 2026-05-26 15:25:57.206368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e015eb383395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_entries',
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('subpath', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('entry_json', sa.JSON(), nullable=False),
    sa.Column('mtime_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('project_key', 'session_id', 'subpath', 'seq')
    )
    op.create_index('ix_session_entries_lookup', 'session_entries', ['project_key', 'session_id', 'subpath'], unique=False)
    op.create_table('session_mtimes',
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('subpath', sa.String(), nullable=False),
    sa.Column('mtime_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('project_key', 'session_id', 'subpath')
    )
    op.create_table('session_summaries',
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('mtime_ms', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('project_key', 'session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summaries')
    op.drop_table('session_mtimes')
    op.drop_index('ix_session_entries_lookup', table_name='session_entries')
    op.drop_table('session_entries')
    # ### end Alembic commands ###
