"""自进化能力 — 管理用户织造的 skill、app 与 workflow 产物."""

from pentaloom.capabilities.weaver.index import WeaverError
from pentaloom.capabilities.weaver.loader import assemble_weaver
from pentaloom.capabilities.weaver.models import (
    AppComponents,
    AppDefinition,
    AppScheduleSpec,
    AppScriptParam,
    AppScriptSpec,
    AppServiceSpec,
    AppWatchSpec,
    AppWindowSpec,
    IndexEntry,
    InvocableAppManifest,
    InvocableAppMeta,
    InvocationExample,
    InvocationSpec,
    InvocationTarget,
    ManifestPermissions,
    SkillFrontmatter,
    SkillMeta,
    WeaverIndex,
    WeaverKind,
    WeaverSource,
)

__all__ = [
    "AppComponents",
    "AppDefinition",
    "AppScheduleSpec",
    "AppScriptParam",
    "AppScriptSpec",
    "AppServiceSpec",
    "AppWatchSpec",
    "AppWindowSpec",
    "IndexEntry",
    "InvocableAppManifest",
    "InvocableAppMeta",
    "InvocationExample",
    "InvocationSpec",
    "InvocationTarget",
    "ManifestPermissions",
    "SkillFrontmatter",
    "SkillMeta",
    "WeaverError",
    "WeaverIndex",
    "WeaverKind",
    "WeaverSource",
    "assemble_weaver",
]
