"""PentaLoom 自定义 MCP 工具 + 权限审批中枢."""

from pentaloom.tools.files import (
    FILE_READ_FULL_NAME,
    FILE_VERIFY_FULL_NAME,
    FILES_MCP_SERVER,
    FILES_MCP_SERVER_NAME,
)
from pentaloom.tools.python_env import (
    INSTALL_LIBS_FULL_NAME,
    PYTHON_ENV_MCP_SERVER_NAME,
    RUN_SCRIPT_FULL_NAME,
)
from pentaloom.tools.search import (
    SEARCH_MCP_SERVER,
    SEARCH_MCP_SERVER_NAME,
    WEB_SEARCH_FULL_NAME,
)
from pentaloom.tools.system_resources import INSTALL_NOTO_SANS_SC_FULL_NAME
from pentaloom.tools.weaver import (
    ALL_WEAVER_FULL_NAMES,
    DELETE_WEAVER_FULL_NAME,
    EDIT_WEAVER_FULL_NAME,
    INSPECT_WEAVER_FULL_NAME,
    LIST_WEAVER_FULL_NAME,
    RUN_WEAVER_FULL_NAME,
    TAIL_WEAVER_LOGS_FULL_NAME,
    WEAVE_SKILL_FULL_NAME,
    WEAVER_MCP_SERVER_NAME,
    build_weaver_mcp_server,
)
from pentaloom.tools.workspace import (
    ALLOW_SESSION_TOOLS,
    BASH_TOOL_NAME,
    FULL_TOOL_NAME as REQUEST_WORKSPACE_DIR_TOOL_NAME,
    HITL_TOOL_NAMES,
    PYTHON_ENV_MCP_SERVER,
    REGISTRY as PERMISSION_REGISTRY,
    WORKSPACE_MCP_SERVER,
    WORKSPACE_MCP_SERVER_NAME,
    allowlist_key,
    build_hitl_hooks,
    make_can_use_tool,
)

# 向后兼容旧 import 名 (LoomPool / routers 还在用 WORKSPACE_REGISTRY).
WORKSPACE_REGISTRY = PERMISSION_REGISTRY

__all__ = [
    "ALLOW_SESSION_TOOLS",
    "ALL_WEAVER_FULL_NAMES",
    "BASH_TOOL_NAME",
    "DELETE_WEAVER_FULL_NAME",
    "EDIT_WEAVER_FULL_NAME",
    "FILE_READ_FULL_NAME",
    "FILE_VERIFY_FULL_NAME",
    "FILES_MCP_SERVER",
    "FILES_MCP_SERVER_NAME",
    "HITL_TOOL_NAMES",
    "INSPECT_WEAVER_FULL_NAME",
    "INSTALL_LIBS_FULL_NAME",
    "INSTALL_NOTO_SANS_SC_FULL_NAME",
    "LIST_WEAVER_FULL_NAME",
    "PERMISSION_REGISTRY",
    "PYTHON_ENV_MCP_SERVER",
    "PYTHON_ENV_MCP_SERVER_NAME",
    "REQUEST_WORKSPACE_DIR_TOOL_NAME",
    "RUN_SCRIPT_FULL_NAME",
    "RUN_WEAVER_FULL_NAME",
    "SEARCH_MCP_SERVER",
    "SEARCH_MCP_SERVER_NAME",
    "TAIL_WEAVER_LOGS_FULL_NAME",
    "WEAVE_SKILL_FULL_NAME",
    "WEAVER_MCP_SERVER_NAME",
    "WEB_SEARCH_FULL_NAME",
    "WORKSPACE_MCP_SERVER",
    "WORKSPACE_MCP_SERVER_NAME",
    "WORKSPACE_REGISTRY",
    "allowlist_key",
    "build_hitl_hooks",
    "build_weaver_mcp_server",
    "make_can_use_tool",
]
