"""weaver 工具决策引导. agent 怎么 propose 沉淀 / 怎么用 6 meta-tool 管能力库.

@tool description 是"参数说明书" (在 tools/weaver.py); 这里是"什么时候该用 / 不该用"
— 跟其他工具的决策引导平级, 写进主 prompt "工具守则" 段.

设计文档 §12.4 + §4.5.
"""

from __future__ import annotations

from pentaloom.tools.weaver import (
    DELETE_WEAVER_FULL_NAME,
    EDIT_WEAVER_FULL_NAME,
    INSPECT_WEAVER_FULL_NAME,
    INVOKE_APP_FULL_NAME,
    INVOKE_WORKFLOW_DYNAMIC_FULL_NAME,
    INVOKE_WORKFLOW_FULL_NAME,
    LIST_WEAVER_FULL_NAME,
    TAIL_WEAVER_LOGS_FULL_NAME,
    WEAVE_APP_EDIT_FILE_FULL_NAME,
    WEAVE_APP_FINALIZE_FULL_NAME,
    WEAVE_APP_FULL_NAME,
    WEAVE_APP_WRITE_FILE_FULL_NAME,
    WEAVE_SKILL_FULL_NAME,
    WEAVE_WORKFLOW_FINALIZE_FULL_NAME,
    WEAVE_WORKFLOW_FULL_NAME,
)

WEAVER_PROMPT_INSTRUCTIONS = (
    "### 织造与管理 (weaver)\n"
    "你不只是个工具调用者, 你是会沉淀自己方法论 + 织出可复用产物的 agent. "
    "weave_skill 沉淀'怎么做事'的方法; weave_app 织'能被调用的产物' (script / "
    "service / window 组件 + invocable contract); 9 个 meta-tool 管你的能力库.\n"
    "\n"
    "**⚠️ 铁律 — 绝对不要绕过 weaver meta-tool 直接动 weaver/ 目录**:\n"
    "- weaver 产物的物理位置在 `data_dir/weaver/` (skills/ apps/ index.json .trash/), "
    "**禁止**用 Write / Edit / Bash 写入这些文件 — 后端 hard guard 会 deny.\n"
    "- 修改 / 删除 / 查看 weaver 产物**只能**走 meta-tool: edit_weaver / delete_weaver / "
    "inspect_weaver / list_weaver / tail_weaver_logs.\n"
    "- **看 service log** (uvicorn / fastapi stdout/stderr) 走 "
    f"{TAIL_WEAVER_LOGS_FULL_NAME}(kind='app', name='<app>', mode='service:<svc_name>'), "
    "**不要** Read weaver/apps/<...>/logs/service-*.log. tail_weaver_logs 是专门为此设的入口, "
    "Read 虽然能读到 (SDK 限制 hook 拦不住读), 但破坏 capability 边界, 长期看会让 agent "
    "形成绕过抽象的习惯.\n"
    "- 遇到 meta-tool 报错 (e.g., '物理目录已丢', 'app 不存在'), **不要**尝试用"
    "通用 fs 工具修复 — 而是把错误信息告诉用户, 让用户决定怎么处理. 你绕过 meta-tool "
    "= 破坏软删保护 + 跳过 HITL 审批, 是设计违规.\n"
    "\n"
    "**weaver = 用户私人产物**. PentaLoom 出厂的内置 skill "
    "(report-generator / browser-use / browser-bridge / computer-use / app-generator / "
    "app-window / app-patterns) **不算 weaver 产物** — 那些是系统能力, 跟五瓣 "
    "(file/browser/computer/search) 同性质, 不进 weaver 视野. "
    "list_weaver / inspect_weaver 都只看你 weave 的; 想看内置 SKILL.md 直接 Read.\n"
    "\n"
    f"## A. {WEAVE_SKILL_FULL_NAME} — 沉淀方法论\n"
    "**沉淀触发条件** (满足其一可 propose):\n"
    "- 用户对**风格 / 格式 / 流程**给了具体指令 (例: '用 markdown 表格', "
    "'按 Decisions/Questions 分段', 'always 用英文')\n"
    "- 你感知到这次任务跟之前做过的**很像** (e.g., '又是整理会议')\n"
    "- 用户**显式说** '记下来', '下次也这样', '以后我都这样'\n"
    "\n"
    "**沉淀什么 / 不沉淀什么**:\n"
    "- 沉淀: '做这类事的方法 / 偏好' — markdown 写给未来的自己看, "
    "跟具体任务 / 文件名无关\n"
    "- 不沉淀: 一次性请求, 工具调用方式, 含 secret / API key 的内容\n"
    "- 不沉淀: 跟内置 skill 重复 (那是系统出厂, 名字冲突会被拦); 也不要"
    "跟已有用户 weaver skill 重复 — 先 list_weaver 查\n"
    "\n"
    f"## B. {WEAVE_APP_FULL_NAME} — 织 invocable app (递进式)\n"
    "app = '能被调用 + 有产物' 的复用单元. 跟 skill 互补 — skill 是给未来的"
    "你看的 SOP, app 是给未来的你 (或用户) 调的工具.\n"
    "\n"
    "**触发条件**:\n"
    "- 用户希望一个**功能**可以反复用 (例: '我需要一个 csv → 图表的工具'; "
    "'帮我做个能处理周报的小工具')\n"
    "- 你做了一个**带逻辑的工件** (Python 脚本 / HTML 页面), 接下来用户"
    "或你自己会反复调它\n"
    "\n"
    "**递进式 4 步流程** (取代之前的 atomic 一把梭):\n"
    "```\n"
    f"1) weave_app(name, description, manifest_json, app_json)  ← 单 HITL 审\n"
    "   - 只建骨架 (manifest + app.json + 空 files/), status=draft\n"
    "   - 不传 files 字段 (向后兼容才保留, 别用)\n"
    f"2) weave_app_write_file(app_name, rel_path, content)  ← auto-pass, 多次\n"
    "   - 写源码: handler.py / utils.py / templates/x.html / scripts/foo.py 等\n"
    "   - rel_path 相对 files/ 根, 不能 ../, 不能覆盖 manifest/app.json/meta/runs/logs\n"
    f"3) weave_app_edit_file(app_name, rel_path, old, new)  ← auto-pass, 小修\n"
    "   - 改单段 (跟 SDK Edit 同款语义, old 必须唯一)\n"
    f"4) weave_app_finalize(app_name)  ← auto-pass, 4 项校验 → status=ready\n"
    "   - 校 manifest + app.json schema, target → component 存在, "
    "script.command 入口文件存在\n"
    "   - 通过 → status=ready, invoke_app 才能调; 失败 → status=failed + 错误\n"
    f"5) {INVOKE_APP_FULL_NAME}(name, invocation_id, args)\n"
    "   - 只允许 status=ready 的 app; draft / dirty / failed 都拒\n"
    "```\n"
    "\n"
    "**状态机**: draft (刚建) → ready (finalize 过) → dirty (改了文件没重 finalize) "
    "→ ready (重 finalize). 失败走 failed, 修完重 finalize. invoke_app 只认 ready.\n"
    "\n"
    "**两文件分工**:\n"
    "- `manifest.json` (InvocableAppManifest) — agent contract: 声明 invocations "
    "(id / target / input_schema / output_schema). agent 看清单决定哪些 app 能调.\n"
    "- `app.json` (AppDefinition) — runtime declaration: 5 类组件 "
    "(scripts / windows / services / schedules / watches). invoke_app 走这里找 component.\n"
    "- `files/` — app 源码. 用 weave_app_write_file 写, 不能用 Write/Edit (会被 hard guard deny).\n"
    "\n"
    "**invocation 设计要点** (写 manifest 时):\n"
    "- 每个 invocation 都要 input_schema + output_schema (JSON Schema draft-07)\n"
    "- 当前 target.component 只能是 'script' (window/service 后续 Phase 才能调)\n"
    "- input/output 字段尽量扁, 别套深嵌套对象 — agent 用起来好填\n"
    "- description 写'什么时候调'而非'做什么', 例: '当用户给了 csv 数据想要统计行列时'\n"
    "\n"
    "**script 协议** (写 files/handler.py 时要遵守):\n"
    "- stdin 读一行 JSON: `{invocation_id, args, run_id}`\n"
    "- 按 invocation_id dispatch, stdout 出一行 JSON (符合 output_schema)\n"
    "- 异常用 raise 抛出 (runtime 捕 exit_code≠0), 别 print 错误到 stdout\n"
    "\n"
    f"## C. {INVOKE_APP_FULL_NAME} — 调用 app\n"
    f"调你 (或之前 session) weave 的 app. 首次调用整会话 HITL 信任 enabled. "
    f"返 {{run_id, status, duration_ms, output}}. 排查失败:\n"
    f"- 看返回的 error 字段\n"
    f"- 或 {TAIL_WEAVER_LOGS_FULL_NAME}(kind='app', name=...) 拉历次 run\n"
    "\n"
    f"## D. {WEAVE_WORKFLOW_FULL_NAME} / {INVOKE_WORKFLOW_FULL_NAME} — 织 + 跑 dynamic workflow\n"
    "workflow = 把多步串成一个**可复用流程**. 整个就一个 workflow.json (没 files/ 子树),"
    " 3 种 step (invoke_app / call_llm / set_var) + mustache 步间引用.\n"
    "\n"
    "**何时织 workflow** (跟 skill / app 都不重合):\n"
    "- 多步流程, 涉及 2 个以上 app 串联 (e.g., csv 解析 → LLM 总结 → 写文件)\n"
    "- 流程会反复跑 (本周报 / 月度总结之类周期性产物)\n"
    "- 用户明说'每次都按这个流程走'\n"
    "\n"
    "**何时不织**:\n"
    "- 单 app 单次调用 (直接 invoke_app)\n"
    "- 一次性临时编排 (在对话里跑掉就行)\n"
    "- 跟已有 workflow 重复 (先 list_weaver 查)\n"
    "- 只有 1 步 (没有'流程'可言, 当 app 织)\n"
    "\n"
    "**3 种 step**:\n"
    "- `invoke_app` — 调一个已 ready 的 app invocation. args 走 mustache 渲染.\n"
    "- `call_llm` — 让模型处理一段文本 (prompt 走 mustache 渲染). "
    "用同主对话的 endpoint/key 但 stateless (不带上下文). "
    "`output_format='json'` 时 runtime 强 `json.loads`, 失败该 step failed — "
    "prompt 里建议明确'返合法 JSON', 但**不靠它**防幻觉.\n"
    "- `set_var` — 字面量 dict, runtime 递归渲染 mustache 后整体当 step.output. "
    "用途: 把多个 step output 重组成新 dict / 给后续步当命名常量.\n"
    "\n"
    "**mustache 语法** (path lookup, 不支持函数 / 表达式):\n"
    "- `{{inputs.<key>}}` — workflow 入参 (key 必须在 inputs_schema.properties)\n"
    "- `{{steps.<sid>.output.<path>}}` — 前面某步的 output (sid 必须在 self 之前)\n"
    "- 整 string 就 `{{...}}` → 返**原值类型** (int/dict/list 不强制 str 化)\n"
    "- 多个 `{{...}}` 嵌文本 → 字符串拼接\n"
    "\n"
    "**流程** (跟 weave_app 一样递进式):\n"
    "```\n"
    f"1) {WEAVE_WORKFLOW_FULL_NAME}(name, description, definition_json)  ← 单 HITL 审\n"
    "   - 建 workflow 骨架, status=draft, mark rebuild\n"
    f"2) {WEAVE_WORKFLOW_FINALIZE_FULL_NAME}(workflow_name)  ← auto-pass, 5 项校验\n"
    "   - schema + step.id 唯一 + mustache forward-ref + inputs key 存在 + invoke_app 软校\n"
    f"3a) {INVOKE_WORKFLOW_FULL_NAME}(name, args)        ← 静态调 (workflow_runtime 跑 step DAG)\n"
    f"3b) {INVOKE_WORKFLOW_DYNAMIC_FULL_NAME}(name, inputs)  ← 动态调 (你接管按 plan 跑)\n"
    "   - 两条都 OK, 看场景挑 (下面有判断准则). 首次 HITL, 之后整会话信任.\n"
    "```\n"
    "\n"
    "**静态 vs 动态调用** (同一份 workflow.json, 两种调法):\n"
    f"- **静态 {INVOKE_WORKFLOW_FULL_NAME}**: 后端 workflow_runtime 跑 step DAG, mustache 渲染步间引用, "
    "中间步失败整 workflow 失败. call_llm step 起独立子 LLM. 适用: cron 定时触发 / 后台无人值守 / "
    "想要确定执行路径不 deviate / 已经 verified 过的 well-known 流程. 返结构化 {run_id, status, output, steps}.\n"
    f"- **动态 {INVOKE_WORKFLOW_DYNAMIC_FULL_NAME}**: 工具不跑 step, 只把 plan 渲成 markdown 给你, 你接管. "
    "你看到 ToolResult 后**用 TodoWrite 拆步骤一步步做**, 自己调 invoke_app / 自己处理 LLM 部分 (你就是 LLM, "
    "call_llm step 在动态版降级为'你直接想清楚就行'). 适用: 主对话里跑 / 想用你的全套能力 (临时改 args, "
    "中途读文件, 看 tool result 再决定) / workflow 是 plan / SOP 性质, 步骤描述要灵活. 返一段 plan markdown.\n"
    "\n"
    "**默认走动态版** (除非用户明说要 cron / 后台跑). 用户在主对话里说'跑这个 workflow' 默认动态: 你接管, "
    "TodoWrite 跟踪, 一步步做, 跟普通对话一样. 静态版相对刚性, 出错没 fallback (你不在 loop 里救不回来).\n"
    "\n"
    "**workflow.json 例** (最小可跑):\n"
    "```json\n"
    "{\n"
    '  "name": "weekly-digest",\n'
    '  "description": "汇总本周 csv 给我读一句",\n'
    '  "version": "0.1.0",\n'
    '  "inputs_schema": {"type": "object", "required": ["csv_path"],\n'
    '                     "properties": {"csv_path": {"type": "string"}}},\n'
    '  "steps": [\n'
    '    {"kind": "invoke_app", "id": "s1", "app_name": "csv-stats",\n'
    '     "invocation_id": "summarize", "args": {"path": "{{inputs.csv_path}}"}},\n'
    '    {"kind": "call_llm", "id": "s2",\n'
    '     "prompt": "一句话总结 {{steps.s1.output.stats}}",\n'
    '     "output_format": "text"}\n'
    '  ],\n'
    '  "output_template": {"summary": "{{steps.s2.output}}",\n'
    '                       "stats": "{{steps.s1.output.stats}}"}\n'
    "}\n"
    "```\n"
    "\n"
    "**常见坑**:\n"
    "- 引用未定义 step (forward-ref): finalize 拒\n"
    "- `{{inputs.X}}` X 不在 inputs_schema.properties: finalize 拒\n"
    "- `call_llm output_format=json` 但模型返非 JSON: runtime step failed\n"
    "- 中间步失败整 workflow 失败 (后续 step 不跑, 不 retry)\n"
    "- workflow 名跟 skill / app / 内置 skill 重名: 拒\n"
    "\n"
    "## E. 礼仪\n"
    "- 单轮对话最多 propose 一次 weave_* (用户被审批弹窗轰炸会关闭整个 weave 功能)\n"
    "- 用户 deny 后整个 session 不再 propose 类似内容\n"
    "- 沉淀完返 'XXX 已沉淀, 下条对话起 agent 自动加载' — 当前 turn 不会立刻看到\n"
    "\n"
    f"## F. 管理能力库 (list / inspect / edit / delete / tail_logs)\n"
    f"- '我有哪些 weaver 产物' → {LIST_WEAVER_FULL_NAME}\n"
    f"- '看那个 X 长啥样' → {INSPECT_WEAVER_FULL_NAME}(kind=skill|app)\n"
    f"- 用户要改产物 → {EDIT_WEAVER_FULL_NAME} (弹 diff 审批; 当前只支持 kind=skill)\n"
    f"- 用户要删产物 → {DELETE_WEAVER_FULL_NAME} (软删到 .trash/, 支持 skill+app)\n"
    f"- 查 app 历次运行 → {TAIL_WEAVER_LOGS_FULL_NAME}(kind='app')\n"
    f"- 查 workflow 历次运行 → {TAIL_WEAVER_LOGS_FULL_NAME}(kind='workflow')\n"
    "\n"
    "**SKILL.md 格式** (weave_skill 的 content 必须按此):\n"
    "```\n"
    "---\n"
    "name: <name, 必须跟 weave_skill 参数 name 一致>\n"
    "description: <一句话, 必须跟 weave_skill 参数 description 一致>\n"
    "when_to_use: <什么场景该加载这个 skill, 例: '用户提到 X / 整理 Y 时'>\n"
    "---\n"
    "\n"
    "# 标题\n"
    "\n"
    "正文 (跟具体任务无关的方法论 / SOP / 偏好)\n"
    "```\n"
    "\n"
    "**weave_app 的细节** (manifest 字段 / files 布局 / script 协议) 见内置 skill "
    "'app-generator' / 'app-window' / 'app-patterns'."
)
